### ISSUE TITLE
Unable to launch module

### ISSUE THREAD

**Issue by bluetardis** [horrorbrood/BossNotes#1]
Updated using curse client to current version... (v1.7.0.9)

Cannot Launch Boss notes in game

Went back to default blizzard UI  - let me know what else I can add in either log files etc to help?

**Comment by bluetardis** [comment]
Rolled back to prior version (v1.7.8) and it works fine

**Comment by horrorbrood** [comment]
Do you have swatter addon can you post the most recent error. I will try it out again fresh install i received no errors but thank you for submitting an issue

**Comment by horrorbrood** [comment]
i am unable to reproduce your issue. try deleting your BossNotes and unzipping manually. it could be an issue with another addon you have

**Comment by horrorbrood** [comment]
Also don't use the releases on this github use the ones in curse

**Comment by bluetardis** [comment]
To update:
-I was using v1.7.0.9 from Curse 
-issue replicable but workaround was to drop back a version 

This morning:
-deleted all boss notes folders
-reinstalled the new version (v1.7.0.10)
-all good

Something buggy with .9 but you guys have resolved it with the current release.

**Comment by bluetardis** [comment]
Close - 1.7.0.10 seems to resolve it

**Comment by horrorbrood** [comment]
Yes .9 had currupted xml files I did not realize they were will add checking xml files after zipping thank you for feedback

**Comment by bluetardis** [comment]
All good - thanks for the quick turnaround.  Will go take it out for a test drive this morning
