### ISSUE TITLE
Error with 7.3

### ISSUE THREAD

**Issue by HnyBear** [horrorbrood/BossNotes#3]
I get the following error when opening bossnotes and another one when closing it. None of my prior notes are showing either. I'm running v1.7.0.19

Date: 2017-08-30 23:28:05
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\BossNotes\BossNotesFrame.lua line 112:
   Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
Debug:
   [C]: PlaySound()
   BossNotes\BossNotesFrame.lua:112: OnShowBossNotesFrame()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [C]: Show()
   ..\FrameXML\UIParent.lua:2441: SetUIPanel()
   ..\FrameXML\UIParent.lua:2282: ShowUIPanel()
   ..\FrameXML\UIParent.lua:2151:
      ..\FrameXML\UIParent.lua:2147
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:2935: ShowUIPanel()
   BossNotes\BossNotes.lua:318:
      BossNotes\BossNotes.lua:314
   (tail call): ?
   ...\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:143:
      ...\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:133
   ...\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:408:
      ...\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:334
   (tail call): ?
   ...\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:769: HandleCommand()
   ...\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:781: ?()
   ..\FrameXML\ChatFrame.lua:4512: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4180: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:2759:
      ..\FrameXML\ChatFrame.lua:2752
   [C]: UseAction()
   ..\FrameXML\SecureTemplates.lua:346: handler()
   ..\FrameXML\SecureTemplates.lua:619:
      ..\FrameXML\SecureTemplates.lua:567
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:264:
      ..\FrameXML\SecureHandlers.lua:261
   [C]: ?
   ..\FrameXML\SecureHandlers.lua:294:
      ..\FrameXML\SecureHandlers.lua:277
   (tail call): ?
Locals:
(*temporary) = "igCharacterInfoOpen"

**Comment by horrorbrood** [comment]
it could be caused by other addons since most of them haven't updated but will try it out thanks for reporting

**Comment by horrorbrood** [comment]
sorry for late response issue is fixed uploading new files to curse thanks!!
